server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: newpassword
    class.name: com.mysql.cj.jdbc.Driver
