server:
  port: 81

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: newpassword
    class.name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true

  cache:
    type: redis
  redis:
    timeout: 10000
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
